export const carTypes = [
    {
        "marca": "CHEVROLET",
        "modelos": [
            "3100",
            "A10",
            "A20",
            "ADVANCED DESIGN",
            "AGILE",
            "AMAZONA",
            "ASTRA",
            "ASTROVAN",
            "AVALANCHE",
            "BEL AIR",
            "BERETTA",
            "BLAZER",
            "BOLT",
            "BONANZA",
            "BRASIL",
            "BRASINCA",
            "C 1504",
            "C10",
            "C14",
            "C15",
            "C20",
            "CALIBRA",
            "CAMARO",
            "CAPRICE",
            "CAPTIVA",
            "CARAVAN",
            "CAVALIER",
            "CELTA",
            "CHEVELLE",
            "CHEVETTE",
            "CHEVY 500",
            "CHEYENNE",
            "CLASSIC",
            "COBALT",
            "COLORADO",
            "CORSA",
            "CORSICA",
            "CORVETTE",
            "CORVETTE GRAND SPORT",
            "COUPÉ",
            "CRUZE",
            "D10",
            "D20",
            "D40",
            "DE LUXE",
            "EL CAMINO",
            "EQUINOX",
            "EXPRESS",
            "FLEETLINE",
            "FLEETMASTER",
            "GRAND BLAZER",
            "HHR",
            "IMPALA",
            "IPANEMA",
            "JOY",
            "KADETT",
            "LUMINA",
            "MALIBU",
            "MARAJÓ",
            "MASTER",
            "MERIVA",
            "MONTANA",
            "MONTE CARLO",
            "MONZA",
            "NOVA",
            "OMEGA",
            "ONIX",
            "OPALA",
            "PICKUP",
            "PRISMA",
            "RAMONA",
            "S10",
            "SATURN",
            "SILVERADO",
            "SONIC",
            "SPACE VAN",
            "SPIN",
            "SPORT VAN",
            "SS",
            "SSR",
            "STYLELINE",
            "STYLEMASTER",
            "SUBURBAN",
            "SUPREMA",
            "SYCLONE",
            "TAHOE",
            "TIGRA",
            "TRACKER",
            "TRAFIC",
            "TRAILBLAZER",
            "TRAVERSE",
            "VAN G20",
            "VECTRA",
            "VEGA",
            "VENTURE",
            "VERANEIO",
            "ZAFIRA"
        ]
    },
    {
        "marca": "FIAT",
        "modelos": [
            "1100",
            "124",
            "128",
            "147",
            "500",
            "500e",
            "600",
            "850",
            "ARGO",
            "BRAVA",
            "BRAVO",
            "CINQUECENTO",
            "COUPÉ",
            "CRONOS",
            "DARDO",
            "DOBLÒ",
            "DUCATO",
            "DUNA",
            "ELBA",
            "FIORINO",
            "FREEMONT",
            "GRAND SIENA",
            "IDEA",
            "LINEA",
            "MAREA",
            "MOBI",
            "OGGI",
            "PALIO",
            "PANORAMA",
            "PREMIO",
            "PULSE",
            "PUNTO",
            "SIENA",
            "SPAZIO",
            "STILO",
            "STRADA",
            "TEMPRA",
            "TIPO",
            "TORO",
            "UNO"
        ]
    },
    {
        "marca": "FORD",
        "modelos": [
            "81A",
            "A",
            "AEROSTAR",
            "ANGLIA",
            "ASPIRE",
            "BELINA",
            "BRONCO",
            "BRONCO SPORT",
            "CLUB WAGON",
            "CONSUL",
            "CONTOUR",
            "CORCEL",
            "CORCEL II",
            "COURIER",
            "CROWN VICTORIA",
            "CUPÊ",
            "CUSTOM",
            "DEL REY",
            "E-350",
            "ECONOLINE",
            "ECOSPORT",
            "EDGE",
            "ESCAPE",
            "ESCORT",
            "EXCURSION",
            "EXPEDITION",
            "EXPLORER",
            "F-1",
            "F-100",
            "F-1000",
            "F-150",
            "F-2000",
            "F-250",
            "F-350",
            "F-4000",
            "F-75",
            "F-MAXX",
            "F3 PICK UP",
            "FAIRLANE",
            "FALCON",
            "FIESTA",
            "FLEX",
            "FOCUS",
            "FURGLAINE",
            "FUSION",
            "GALAXIE",
            "GT",
            "IBIZA",
            "JEEP",
            "KA",
            "KA +",
            "LANDAU",
            "LTD",
            "MAVERICK",
            "MONDEO",
            "MUSTANG",
            "MUSTANG V6",
            "PAMPA",
            "PHAETON",
            "PICK UP",
            "PROBE",
            "RANCHERO",
            "RANGER",
            "ROYALE",
            "RURAL",
            "SIERRA",
            "SLANTBACK",
            "SPORT TRAC",
            "SUPER DELUXE",
            "T",
            "TAURUS",
            "TERRITORY",
            "THUNDERBIRD",
            "TORINO",
            "TRANSIT",
            "TUDOR",
            "VAU",
            "VERONA",
            "VERSAILLES",
            "VICTORIA",
            "WINDSTAR"
        ]
    },
    {
        "marca": "HONDA",
        "modelos": [
            "ACCORD",
            "CITY",
            "CIVIC",
            "CRV",
            "FIT",
            "HR-V",
            "INSIGHT",
            "LEGEND",
            "ODYSSEY",
            "PASSPORT",
            "PILOT",
            "PRELUDE",
            "RIDGELINE",
            "S2000",
            "S800",
            "WR-V"
        ]
    },
    {
        "marca": "HYUNDAI",
        "modelos": [
            "ACCENT",
            "ATOS",
            "AZERA",
            "CENTENNIAL",
            "COUPÊ",
            "CRETA",
            "ELANTRA",
            "EQUUS",
            "EXCEL",
            "GALLOPER",
            "GENESIS",
            "GRAND SANTA FÉ",
            "H1 STAREX",
            "H100",
            "HB20",
            "HB20S",
            "HB20X",
            "HR",
            "I30",
            "I30 CW",
            "IX35",
            "MATRIX",
            "PORTER",
            "S-COUPÉ",
            "SANTA FÉ",
            "SONATA",
            "TERRACAN",
            "TIBURON",
            "TRAJET",
            "TUCSON",
            "VELOSTER",
            "VERACRUZ"
        ]
    },
    {
        "marca": "MITSUBISHI",
        "modelos":[
            "3000 GT",
            "AIRTREK",
            "ASX",
            "COLT",
            "DIAMANT",
            "ECLIPSE",
            "ECLIPSE CROSS",
            "ECLIPSE SPYDER",
            "ENDEAVOR",
            "EXPO",
            "GALANT",
            "GRANDIS",
            "i-MiEV",
            "L200",
            "L200 OUTDOOR",
            "L200 SAVANA",
            "L200 TRITON",
            "L300",
            "LANCER",
            "MIRAGE",
            "MONTERO",
            "OUTLANDER",
            "OUTLANDER SPORT",
            "PAJERO",
            "PAJERO DAKAR",
            "PAJERO FULL",
            "PAJERO IO",
            "PAJERO SPORT",
            "PAJERO TR4",
            "RAIDER",
            "SPACE WAGON"
          ]
    },
    {
        "marca": "NISSAN",
        "modelos":[
            "240SX",
            "280Z",
            "280ZX",
            "300 ZX",
            "350Z",
            "370Z",
            "ALTIMA",
            "ARMADA",
            "AX",
            "CUBE",
            "D",
            "D 21",
            "FRONTIER",
            "GRAND LIVINA",
            "GT-R",
            "INFINITI",
            "JUKE",
            "KICKS",
            "KING CAB",
            "LEAF",
            "LIVINA",
            "MARCH",
            "MAXIMA",
            "MICRA",
            "MURANO",
            "NX",
            "PATHFINDER",
            "PATROL",
            "PICK-UP",
            "PRIMERA",
            "QUEST",
            "ROGUE",
            "SENTRA",
            "SILVIA",
            "SKYLINE",
            "STANZA",
            "TERRANO",
            "TIIDA",
            "VAN",
            "VERSA",
            "X-TRAIL",
            "XTERRA"
          ]
    },
    {

        "marca": "PEUGEOT",
        "modelos":[
            "106",
            "2008",
            "205",
            "206",
            "207",
            "208",
            "3008",
            "306",
            "307",
            "308",
            "308cc",
            "309",
            "405",
            "406",
            "407",
            "408",
            "5008",
            "504",
            "505",
            "508",
            "605",
            "607",
            "806",
            "807",
            "BOXER",
            "EXPERT",
            "HOGGAR",
            "ION",
            "PARTNER",
            "PARTNER RAPID",
            "RCZ"
          ]
    },
    {
        "marca": "RENAULT",
        "modelos":[
            "16",
            "19",
            "21",
            "CAPTUR",
            "CLIO",
            "DAUPHINE",
            "DUSTER",
            "DUSTER OROCH",
            "EXPRESS",
            "FLUENCE",
            "GORDINI",
            "GRAND SCÉNIC",
            "JUVAQUATRE",
            "KANGOO",
            "KWID",
            "LAGUNA",
            "LOGAN",
            "MASTER",
            "MÉGANE",
            "OROCH",
            "SAFRANE",
            "SANDERO",
            "SCÉNIC",
            "SYMBOL",
            "TRAFIC",
            "TWINGO",
            "TWIZY",
            "ZOE"
          ]
    },
    {

        "marca": "TOYOTA",
        "modelos":[
            "4RUNNER",
            "AVALON",
            "BANDEIRANTE",
            "BJ",
            "CAMRY",
            "CELICA",
            "COROLLA",
            "COROLLA CROSS",
            "CORONA",
            "ETIOS",
            "ETIOS CROSS",
            "FIELDER",
            "FJ CRUISER",
            "HIGHLANDER",
            "HILUX",
            "HILUX SW4",
            "LAND",
            "LAND CRUISER",
            "LAND CRUISER PRADO",
            "LEXUS",
            "MATRIX",
            "MR-2",
            "PASEO",
            "PREMIO",
            "PREVIA",
            "PRIUS",
            "RAV4",
            "SEQUOIA",
            "SIENNA",
            "STARLET",
            "SUPRA",
            "T-100",
            "TACOMA",
            "TERCEL",
            "TRIP",
            "TUNDRA",
            "VENZA",
            "YARIS"
          ]
    },
    {
        "marca": "VOLKSWAGEN",
        "modelos":[
            "1200",
            "1300",
            "1500",
            "1600",
            "181 KURIERWAGEN",
            "AMAROK",
            "APOLLO",
            "BORA",
            "BRASILIA",
            "BUGGY",
            "CARAVELLE",
            "CORRADO",
            "CROSS UP",
            "CROSSFOX",
            "EOS",
            "EUROVAN",
            "FOX",
            "FUSCA",
            "GOL",
            "GOLF",
            "JETTA",
            "KARMANN-GHIA",
            "KOMBI",
            "LOGUS",
            "MG SPAIC",
            "NEW BEETLE",
            "NIVUS",
            "PARATI",
            "PASSAT",
            "PASSAT VARIANT",
            "POINTER",
            "POLO",
            "POLO SEDAN",
            "QUANTUM",
            "SANTANA",
            "SAVEIRO",
            "SCIROCCO",
            "SP2",
            "SPACE CROSS",
            "SPACEFOX",
            "T-CROSS",
            "TAOS",
            "TIGUAN",
            "TL",
            "TOUAREG",
            "TRANSPORTER",
            "UP",
            "VAN",
            "VARIANT",
            "VARIANT II",
            "VIRTUS",
            "VOYAGE",
            "XL1"
          ]
    },
    {

        "marca": "VOLVO",
        "modelos":[
            "440",
            "444",
            "460",
            "850",
            "855",
            "940",
            "960",
            "C30",
            "C40",
            "C70",
            "S40",
            "S60",
            "S70",
            "S80",
            "S90",
            "V40",
            "V50",
            "V60",
            "V70",
            "XC40",
            "XC60",
            "XC70",
            "XC90"
          ]
    }
]